
import ayarlar.actionayar;
import ayarlar.duzen;
import ayarlar.iconayarlari;
import java.awt.Color;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author slael
 */
public class Hesapekranı extends javax.swing.JFrame implements duzen {

    /**
     * Creates new form Hesapekranı
     */
    public Hesapekranı() {
        initComponents();
        getEdits();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        hesapekranıpanel = new javax.swing.JPanel();
        hoşglabel = new javax.swing.JLabel();
        adsoyadlabel = new javax.swing.JLabel();
        bakiyetext = new javax.swing.JLabel();
        bakiyefoto = new javax.swing.JLabel();
        pçbutton = new javax.swing.JButton();
        pytext = new javax.swing.JButton();
        havalebutton = new javax.swing.JButton();
        ödebutton = new javax.swing.JButton();
        pçfoto = new javax.swing.JLabel();
        pyfoto = new javax.swing.JLabel();
        havalefoto = new javax.swing.JLabel();
        ödefoto = new javax.swing.JLabel();
        out = new javax.swing.JLabel();
        settings = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ALABANK Hesap Ekranı");

        hesapekranıpanel.setBackground(new java.awt.Color(255, 204, 102));
        hesapekranıpanel.setForeground(new java.awt.Color(102, 102, 102));

        hoşglabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hoşglabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hoşglabel.setText("HOŞGELDİNİZ");

        adsoyadlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        adsoyadlabel.setForeground(new java.awt.Color(0, 102, 102));
        adsoyadlabel.setText("[KULLANICI ADI SOYADI]");

        bakiyetext.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        bakiyetext.setForeground(new java.awt.Color(51, 0, 0));
        bakiyetext.setText("[BAKİYE]");

        bakiyefoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/para.png"))); // NOI18N

        pçbutton.setBackground(new java.awt.Color(204, 102, 0));
        pçbutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pçbutton.setForeground(new java.awt.Color(51, 0, 0));
        pçbutton.setText("PARA ÇEK");
        pçbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pçbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pçbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pçbuttonMouseExited(evt);
            }
        });
        pçbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pçbuttonActionPerformed(evt);
            }
        });

        pytext.setBackground(new java.awt.Color(204, 102, 0));
        pytext.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pytext.setText("PARA YATIR");
        pytext.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pytext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pytextMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pytextMouseExited(evt);
            }
        });
        pytext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pytextActionPerformed(evt);
            }
        });

        havalebutton.setBackground(new java.awt.Color(204, 102, 0));
        havalebutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        havalebutton.setText("HAVALE");
        havalebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        havalebutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                havalebuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                havalebuttonMouseExited(evt);
            }
        });
        havalebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                havalebuttonActionPerformed(evt);
            }
        });

        ödebutton.setBackground(new java.awt.Color(204, 102, 0));
        ödebutton.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        ödebutton.setText("ÖDEMELER");
        ödebutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ödebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ödebuttonActionPerformed(evt);
            }
        });

        pçfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/paraçek.png"))); // NOI18N
        pçfoto.setText("jLabel3");

        pyfoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/parayatır.png"))); // NOI18N
        pyfoto.setText("jLabel2");

        havalefoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/ödeme.png"))); // NOI18N
        havalefoto.setText("jLabel5");

        ödefoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/havale.png"))); // NOI18N
        ödefoto.setText("jLabel6");
        ödefoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ödefotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ödefotoMouseExited(evt);
            }
        });

        out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/out.png"))); // NOI18N
        out.setText("jLabel1");
        out.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        out.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                outMouseClicked(evt);
            }
        });

        settings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconlar/settings.png"))); // NOI18N
        settings.setText("jLabel2");
        settings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout hesapekranıpanelLayout = new javax.swing.GroupLayout(hesapekranıpanel);
        hesapekranıpanel.setLayout(hesapekranıpanelLayout);
        hesapekranıpanelLayout.setHorizontalGroup(
            hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(adsoyadlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(pçfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesapekranıpanelLayout.createSequentialGroup()
                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(pçbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(out, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesapekranıpanelLayout.createSequentialGroup()
                        .addComponent(hoşglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(207, 207, 207)
                        .addComponent(settings, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesapekranıpanelLayout.createSequentialGroup()
                        .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(pyfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bakiyefoto, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                                .addComponent(bakiyetext, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(117, 117, 117))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesapekranıpanelLayout.createSequentialGroup()
                                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ödebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ödefoto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                                        .addGap(64, 64, 64)
                                        .addComponent(havalefoto, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hesapekranıpanelLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(havalebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(59, 59, 59))))))
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(pytext))))
        );
        hesapekranıpanelLayout.setVerticalGroup(
            hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(out))
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(hoşglabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(settings)))
                .addGap(41, 41, 41)
                .addComponent(adsoyadlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(bakiyetext, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hesapekranıpanelLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(bakiyefoto, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pçfoto)
                    .addComponent(pyfoto)
                    .addComponent(ödefoto)
                    .addComponent(havalefoto))
                .addGap(45, 45, 45)
                .addGroup(hesapekranıpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pytext, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pçbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ödebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(havalebutton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hesapekranıpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(hesapekranıpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void getEdits() {
        this.setLocationRelativeTo(null);
        hesapekranıpanel.setFocusable(true);
    }
    
    /*
    buton renklendirmeleri ve icon değişimleri
    */
   
    private void pçbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pçbuttonActionPerformed
        actionayar.setVisible(this, new paraçekmeekrani());
    }//GEN-LAST:event_pçbuttonActionPerformed

    private void pytextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pytextActionPerformed
        actionayar.setVisible(this, new parayatirmaekrani());
    }//GEN-LAST:event_pytextActionPerformed

    private void ödebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ödebuttonActionPerformed
        actionayar.setVisible(this, ödemelerekrani());
    }//GEN-LAST:event_ödebuttonActionPerformed

    private void pçbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pçbuttonMouseEntered
        this.setBgFg(evt.getComponent());
        iconayarlari.changeIcon(pçfoto,"paraçek2")
    }//GEN-LAST:event_pçbuttonMouseEntered

    private void pçbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pçbuttonMouseExited
       MainClass.setOriginalBgFg(JButton) evt.getComponent();
       iconayarlari.setOrginalIcon(pçfoto);
    }//GEN-LAST:event_pçbuttonMouseExited

    private void pytextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pytextMouseEntered
        this.setBgFg(evt.getComponent());
        iconayarlari.changeIcon(pyfoto,"parayatır2")
    }//GEN-LAST:event_pytextMouseEntered

    private void pytextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pytextMouseExited
        MainClass.setOriginalBgFg(JButton) evt.getComponent();
        iconayarlari.setOrginalIcon(pyfoto);
    }//GEN-LAST:event_pytextMouseExited

    private void ödefotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ödefotoMouseEntered
        this.setBgFg(evt.getComponent());
        iconayarlari.changeIcon(ödefoto,"ödeme2")
    }//GEN-LAST:event_ödefotoMouseEntered

    private void ödefotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ödefotoMouseExited
        MainClass.setOriginalBgFg(JButton) evt.getComponent();
        iconayarlari.setOrginalIcon(ödefoto);
        
    }//GEN-LAST:event_ödefotoMouseExited

    private void havalebuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_havalebuttonMouseEntered
        this.setBgFg(evt.getComponent());
        iconayarlari.changeIcon(havalefoto,"havale2")
    }//GEN-LAST:event_havalebuttonMouseEntered

    private void havalebuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_havalebuttonMouseExited
     MainClass.setOriginalBgFg(JButton) evt.getComponent();   
     iconayarlari.setOrginalIcon(havalefoto);
    }//GEN-LAST:event_havalebuttonMouseExited

    private void havalebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_havalebuttonActionPerformed
        actionayar.setVisible(this, havaleekrani());
    }//GEN-LAST:event_havalebuttonActionPerformed

    private void outMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_outMouseClicked
        actionayar.setVisible(this, KullaniciGirişi());
    }//GEN-LAST:event_outMouseClicked

    private void settingsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsMouseClicked
       actionayar.setVisible(this,ayarlarekrani());
    }//GEN-LAST:event_settingsMouseClicked

    private void setBgFg(Compenent c) {
        MainClass.setBgFg((JButton)c,Color.black,Color.white);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hesapekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hesapekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hesapekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hesapekranı.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hesapekranı().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adsoyadlabel;
    private javax.swing.JLabel bakiyefoto;
    private javax.swing.JLabel bakiyetext;
    private javax.swing.JButton havalebutton;
    private javax.swing.JLabel havalefoto;
    private javax.swing.JPanel hesapekranıpanel;
    private javax.swing.JLabel hoşglabel;
    private javax.swing.JLabel out;
    private javax.swing.JLabel pyfoto;
    private javax.swing.JButton pytext;
    private javax.swing.JButton pçbutton;
    private javax.swing.JLabel pçfoto;
    private javax.swing.JLabel settings;
    private javax.swing.JButton ödebutton;
    private javax.swing.JLabel ödefoto;
    // End of variables declaration//GEN-END:variables
}
